/* =============================================================================
 * messages.js — every string the backend can return to a browser, in both
 * languages. Nothing here is generated by a model, so a failure path always
 * produces coherent copy in the customer's own language.
 * ========================================================================== */

export const DISCLAIMER = {
  en: 'This is an initial approximate estimate and may increase or decrease after a short requirements meeting.',
  ar: 'هذا تقدير مبدئي تقريبي، وقد يزيد أو يقل بعد اجتماع قصير لفهم المتطلبات بشكل أدق.',
};

/** Used whenever the model gave us nothing usable for a field. */
export function quoteFallbacks(language, projectTypeLabel) {
  return language === 'ar'
    ? {
        summary: `تقدير مبدئي لمشروع ${projectTypeLabel} بناءً على ما ورد في طلبك.`,
        scope: ['تحديد المتطلبات الأساسية', 'بناء النسخة الأولى القابلة للاستخدام', 'اختبار وتسليم'],
        timeline: 'يُحدَّد بعد اجتماع المتطلبات',
        assumptions: ['التقدير مبني على أقل نطاق عملي للمشروع'],
        message:
          'شكرًا لتواصلك. راجعتُ طلبك وأعددتُ نطاقًا سعريًا مبدئيًا بناءً على ما وصفته. ' +
          'النطاق الأدق يحتاج اجتماعًا قصيرًا لفهم المتطلبات، وبعده يمكن تثبيت السعر والمدة.',
        cta: 'احجز اجتماعًا قصيرًا عبر واتساب',
        disclaimer: DISCLAIMER.ar,
      }
    : {
        summary: `A preliminary estimate for a ${projectTypeLabel} project, based on what you described.`,
        scope: ['Agree the core requirements', 'Build the first usable version', 'Test and hand over'],
        timeline: 'To be confirmed after the requirements meeting',
        assumptions: ['The estimate assumes a minimum viable scope'],
        message:
          'Thanks for getting in touch. I have read your request and put together a preliminary range ' +
          'based on what you described. A short requirements meeting is what turns this into a firm ' +
          'price and timeline.',
        cta: 'Book a short meeting on WhatsApp',
        disclaimer: DISCLAIMER.en,
      };
}

/** Public, non-revealing error copy. Codes are stable; wording is localised. */
export const ERRORS = {
  validation: {
    en: 'Some details need a second look. Please check the highlighted fields.',
    ar: 'بعض البيانات تحتاج مراجعة. من فضلك تحقق من الحقول المحددة.',
  },
  rateLimited: {
    en: 'That is a few requests in a short time. Please try again in a minute.',
    ar: 'تم إرسال عدة طلبات خلال وقت قصير. من فضلك حاول بعد دقيقة.',
  },
  tooLarge: {
    en: 'That request is larger than the form accepts. Please shorten the description.',
    ar: 'حجم الطلب أكبر مما يقبله النموذج. من فضلك اختصر الوصف.',
  },
  botCheck: {
    en: 'We could not verify this submission. Please reload the page and try again.',
    ar: 'تعذّر التحقق من هذا الإرسال. من فضلك أعد تحميل الصفحة وحاول مرة أخرى.',
  },
  server: {
    en: 'Something went wrong on our side. Your request was not lost — please try again shortly.',
    ar: 'حدث خطأ لدينا. لم يُفقد طلبك — من فضلك حاول مرة أخرى بعد قليل.',
  },
  /* The lead is saved; only the AI step failed. Said plainly, because the
     customer has in fact reached Mohamed and should know it. */
  aiUnavailable: {
    en: 'Your request has been received and sent to Mohamed. The automatic estimate is temporarily unavailable, so he will reply with a quote personally.',
    ar: 'تم استلام طلبك وإرساله إلى محمد. التقدير التلقائي غير متاح مؤقتًا، لذلك سيرد عليك بعرض السعر شخصيًا.',
  },
};

export const PROJECT_TYPE_LABELS = {
  portfolio:           { en: 'portfolio site',          ar: 'موقع أعمال شخصي' },
  simple_website:      { en: 'business website',        ar: 'موقع تعريفي للشركة' },
  advanced_website:    { en: 'dynamic web application', ar: 'تطبيق ويب ديناميكي' },
  backend_api:         { en: 'backend / API',           ar: 'خدمات خلفية / واجهات برمجية' },
  automation:          { en: 'automation / integration',ar: 'أتمتة / تكامل' },
  data_ai:             { en: 'data / AI',               ar: 'بيانات / ذكاء اصطناعي' },
  mobile_app:          { en: 'mobile app',              ar: 'تطبيق جوال' },
  erp_business_system: { en: 'ERP / business system',   ar: 'نظام ERP / نظام أعمال' },
  other:               { en: 'software',                ar: 'برمجي' },
};

export function projectTypeLabel(type, language) {
  const row = PROJECT_TYPE_LABELS[type] || PROJECT_TYPE_LABELS.other;
  return row[language] || row.en;
}

export function errorBody(code, language) {
  const row = ERRORS[code] || ERRORS.server;
  return { ok: false, code, message: row[language === 'ar' ? 'ar' : 'en'] };
}
